version: '3.9'
services:
  database:
    image: 'postgres'
    restart: always
    volumes:
      - data:/data/db
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  backend:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    container_name: eduhub_api
    env_file:
      - .env
    depends_on:
      - database
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - database
volumes:
  data:
